# Exercise: Functional Paradigm - Sum of Squares

""" 
Task: 
Define a function called functional_example that calculates the sum of squares of numbers in a list using functional programming techniques. 
Use Python's generator expression to apply a square function to each element of the list and then sum the squared values.

"""

"""
Steps:
1. Define the function functional_example(numbers) that takes a list of numbers as input.
2. Inside the function, use a generator expression to calculate the square of each number in the list.
3. Use the sum() function to sum up the squared values generated by the expression.
4. Return the sum of squares.
5. Create a sample list of numbers.
6. Call the functional_example function with the sample list of numbers.
7. Display the result, which is the sum of squares of the numbers in the list.

"""

def functional_example(numbers):
    # Your code goes here:
    pass